repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        stages: [commit]
    -   id: end-of-file-fixer
        stages: [commit]
    -   id: check-yaml
        stages: [commit]
    -   id: debug-statements
        stages: [commit]
    -   id: double-quote-string-fixer
        stages: [commit]
    -   id: name-tests-test
        stages: [commit]
    -   id: requirements-txt-fixer
        stages: [commit]

-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    -   id: setup-cfg-fmt
        stages: [commit]

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        stages: [commit]
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py39-plus, --add-import, 'from __future__ import annotations']

# -   repo: https://github.com/asottile/add-trailing-comma
#     rev: v3.1.0
#     hooks:
#     -   id: add-trailing-comma
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
    -   id: pyupgrade
        stages: [commit]
        args: [--py39-plus]
# -   repo: https://github.com/hhatto/autopep8
#     rev: v2.0.4
#     hooks:
#     -   id: autopep8
# -   repo: https://github.com/PyCQA/flake8
#     rev: 7.0.0
#     hooks:
#     -   id: flake8
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.9.0
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-all]
#         exclude: ^testing/resources/
