[tool.poetry]
name = "pyscirec"
version = "0.1.0"
description = ""
authors = ["William Espinoza <wmespi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
spotipy = "^2.23.0"
pandas = "^2.2.1"
requests = "^2.31.0"
lyricsgenius = "^3.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
